eth_dbt_cert_prep:
  outputs:
    ci:
      account: lngyjcn-wr36723
      database: CI
      private_key_path: "{{ env_var('DBT_PRIVATE_KEY_PATH') }}"
      role: ACCOUNTADMIN
      schema: CI_SCHEMA
      threads: 1
      type: snowflake
      user: alif
      warehouse: COMPUTE_WH
  target: ci